export enum ActionsType {
  ADD_TO_CART = "ADD_TO_CART",

  CHECK_USER_END = "CHECK_USER_END",
  CHECK_USER_START = "CHECK_USER_START",
  CLEAR_CART = "CLEAR_CART",
  CLEAR_FORM_VALUES = "CLEAR_FORM_VALUES",
  COUNT_CART_TOTALS = "COUNT_CART_TOTALS",

  FORM_SUBMITTED = "FORM_SUBMITTED",

  HANDLE_FORM_INPUT = "HANDLE_FORM_INPUT",
  HIDE_ALERT_MESSAGE = "HIDE_ALERT_MESSAGE",
  HIDE_ORDER_MODAL = "HIDE_ORDER_MODAL",

  LOGIN_ERROR = "LOGIN_ERROR",

  NEWSLETTER_SUBSCRIPTION_ERROR = "NEWSLETTER_SUBSCRIPTION_SUCCESS",
  NEWSLETTER_SUBSCRIPTION_SUCCESS = "NEWSLETTER_SUBSCRIPTION_SUCCESS",

  ORDER_SUCCESS = "ORDER_SUCCESS",

  REMOVE_CART_ITEM = "REMOVE_CART_ITEM",

  SET_USER = "SET_USER",
  SHOW_ALERT_MESSAGE = "SHOW_ALERT_MESSAGE",
  SHOW_ORDER_MODAL = "SHOW_ORDER_MODAL",

  TOGGLE_ITEM_AMOUNT = "TOGGLE_ITEM_AMOUNT",
}
