export enum ActionsType {
  ADD_TO_CART = "ADD_TO_CART",
  COUNT_CART_TOTALS = "COUNT_CART_TOTALS",
  REMOVE_CART_ITEM = "REMOVE_CART_ITEM",
  TOGGLE_ITEM_AMOUNT = "TOGGLE_ITEM_AMOUNT",
  CLEAR_CART = "CLEAR_CART",

  FORM_SUBMITTED = "FORM_SUBMITTED",
  HANDLE_FORM_INPUT = "HANDLE_FORM_INPUT",
  NEWSLETTER_SUBSCRIPTION_SUCCESS = "NEWSLETTER_SUBSCRIPTION_SUCCESS",
  NEWSLETTER_SUBSCRIPTION_ERROR = "NEWSLETTER_SUBSCRIPTION_SUCCESS",
}
